baseURL: https://yizhen1106-portfolio.netlify.app/
languageCode: en-us
title: Yizhen Zhang Portfolio
theme: aafu
params:
  aboutme:
    description: My name is Yizhen Zhang and I will graduate with M.S. degree in Urban informatics this summer from Northeastern University, Boston, MA. I built this website using blogdow package in R-Studio and here, you can read about my background, my interests, my work, and experiences.
    icon: fas fa-user
    title: About Me
  author: Yizhen Zhang 
  copyright: short copyright message
  description: Website title
  education:
    icon: fas fa-graduation-cap
    list:
      - college: University of Northeastern Boston Campus
        dates: Fall 2021 - Summer 2022
        degree: M.S. in Urban informatics
        
      - college: University of Colorado Boulder
        dates: Fall 2016 - Spring 2021
        degree: B.S. in Geography
    title: Education
  experience:
    icon: fas fa-briefcase
    list:
      - company: Northeastern-Research Practicum
        dates: May 2022 - *Present*
        details: I was fortunate to have a opportunity to work with Professor Wang (Ryan Wang). We are working a project about Predicting the mobility pattern in city when the natural hazards happened, especially wildfire.In this project, I was focusing on the wildfire in California and the relationship bewteen air quality and mobility data. Analysis the daily mobility data and air quality data monitering wildfire cases that affect air quality and finding correlation and regression bewteen them. Eventually, considering other elements such as gender, race population, population density on different block group, travel distance & travel time, build a multi-regression model apply to our final prediction model. Ultimately, apply this prediction model into an APPs on phones which can tell people which specific location or area have health risk, avoiding people visit those areas. 
        position: Research Assissant
        
      
      - company: CMIC Technology Ltd. 
        dates: April 2022 - *Present*
        details: Cooperate with the project manager to carry out the research of "Economic Impact and Policy Suggestions of New Infrastructure Industry" of the 2021 High-end Science and Technology Innovation Intellectual database Youth Project of China Association for Science and Technology. Cooperate with the project manager to carry out projects related to the transformation of the Hainan government's digital intelligence, responsible for data collection and data analysis.
        position: Intern (remote)
   
    title: Experiences
  favicons:
    metas: "        <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"apple-touch-icon.png\">\n
      \       <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"favicon-32x32.png\">\n
      \       <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"favicon-16x16.png\">\n
      \       <link rel=\"manifest\" href=\"site.webmanifest\">\n        <link rel=\"mask-icon\"
      href=\"safari-pinned-tab.svg\" color=\"#252627\">\n        <link rel=\"shortcut
      icon\" href=\"favicon.ico\">\n        "
    use: yes
  hobby:
    icon: fas fa-gamepad
    list:
      - hobby: Workout
      - hobby: Video games
      - hobby: Cat person
    title: Hobbies
  profile:
    location: Beijing, China
    name: Yizhen Zhang
    photo: Portfolio_image.jpg
    tagline: M.S. Urban informatics
  project:
    icon: fas fa-project-diagram
    list:
      - description: Description of the project
        title: Project 1
        url: '#'
      - description: Description of the project
        title: Project 2
        url: '#'
      - description: Description of the project
        title: Project 3
        url: '#'
    title: Projects
  showInAccordion:
    - expand: yes
      item: aboutme
    - item: experience
    - item: education
    - item: publication
    - item: project
    - item: skill
    - item: hobby
  skill:
    icon: fas fa-cogs
    list:
      - skill:  ArcGIS, QGIS
        skillrating: 90
      - skill: R-studio
        skillrating: 80
      - skill: SQL
        skillrating: 50
      - skill: Mongodb
        skillrating: 30
      - skill: English
        skillrating: 85
      - skill: Japanese
        skillrating: 35
    panelId: skill-panel
    title: Skills
  social:
    list:
      - icon: fab fa-linkedin-in
        title: LinkedIn
        url: 'https://www.linkedin.com/in/yizhen-zhang-949039234/'
      - icon: fab fa-github
        title: GitHub
        url: 'https://github.com/YizhenZhang1106'
      - icon: fab fa-instagram
        title: Instagram
        url: 'https://www.instagram.com/yizhenzhang_tony/'
    title: Links
  theme:
    mainTheme: ocean
    showAttribute: yes
    singlePage: no
  title: Aafu theme
