baseURL = "https://yizhen1106-portfolio.netlify.app/"
languageCode = "en-us"
theme = "aafu"

[params]
    title = "Aafu theme"
    author = "Yizhen Zhang"
    description = "Website title"
    copyright = "short copyright message"

    [params.theme]
        # Available themes are 'light', 'dark', 'ocean', and 'pinkish'
        mainTheme = "ocean"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = false
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Yizhen Zhang."
        tagline = "M.S. Urban informatics"
        location = "Beijing, China"
        photo = "Portfolio_image.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            icon = "fab fa-linkedin-in"
            url = "https://www.linkedin.com/in/yizhen-zhang-949039234/"
            title = "LinkedIn"		
        [[params.social.list]]
            icon = "fab fa-github"
            url = "https://github.com/YizhenZhang1106"
            title = "GitHub"
        [[params.social.list]]
            icon = "fab fa-instagram"
            url = "https://www.instagram.com/yizhenzhang_tony/"
            title = "Instagram"
        [[params.social.list]]
            icon = "fab fa-envelope"
            url = "mailto:zhangyizhen025@gmail.com"
            title = "E-mail"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "poster"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "My name is Yizhen Zhang and I will graduate with M.S. degree in Urban informatics this summer from Northeastern University, Boston, MA. I built this website using blogdown package in R-Studio and here, you can read about my background, my interests, my work, and experiences."

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Research Assisant"
            dates = "May 2022 - *Present*"
            company = "Northeastern University"
            details = "I was fortunate to have a opportunity to work with Professor Wang (Ryan Wang). We are working a project about Predicting the mobility pattern in city when the natural hazards happened, especially wildfire.In this project, I was focusing on the wildfire in California and the relationship bewteen air quality and mobility data. Analysis the daily mobility data and air quality data monitering wildfire cases that affect air quality and finding correlation and regression bewteen them. Eventually, considering other elements such as gender, race population, population density on different block group, travel distance & travel time, build a multi-regression model apply to our final prediction model. Ultimately, apply this prediction model into an APPs on phones which can tell people which specific location or area have health risk, avoiding people visit those areas."
        [[params.experience.list]]
            position = "Intern (Remote)"
            dates = "April 2022 - *Present*"
            company = "CMIC Technology Ltd. "
            details ="Cooperate with the project manager to carry out the research of 'Economic Impact and Policy Suggestions of New Infrastructure Industry' of the 2021 High-end Science and Technology Innovation Intellectual database Youth Project of China Association for Science and Technology. Cooperate with the project manager to carry out projects related to the transformation of the Hainan government's digital intelligence, responsible for data collection and data analysis."

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"
        [[params.education.list]]
            degree = "M.S. in Urban informatics"
            college = "Northeastern University-Boston"
            dates = "Fall 2021 - Summer 2022"
        [[params.education.list]]
            degree = "B.A. in Geography"
            college = "University of Colorado-Boulder"
            dates = "Fall 2016 - Spring 2021"

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "Project 1"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "Project 2"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "Project 3"
            url = "#"
            description = "Description of the project"
            
    # Poster section
    [params.poster]
      title = "Posters"
      icon = "fas fa-project-diagram"
     
      [[params.poster.list]]
            title = "poster 1"
            url = "#"
            description = "Description of the project"
      [[params.poster.list]]
            title = "poster 2"
            url = "#"
            description = "Description of the project"
      [[params.poster.list]]
            title = "poster 3"
            url = "#"
            description = "Description of the project"  
      
    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Skill 1, Skill 2"
            skillrating = 90
        [[params.skill.list]]
            skill = "Skill 3"
            skillrating = 80
        [[params.skill.list]]
            skill = "Skill 4"
            skillrating = 50
        [[params.skill.list]]
            skill = "Skill 5"
            skillrating = 40
        [[params.skill.list]]
            skill = "Skill 6"
            skillrating = 30
       

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"

        [[params.hobby.list]]
            hobby = "Fitness"
        [[params.hobby.list]]
            hobby = "Hiking"
        [[params.hobby.list]]
            hobby = "Video Gaming"